// <auto-generated />
using System;
using CareerConnect.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerConnect.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917193058_AddInterviewTracker")]
    partial class AddInterviewTracker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerConnect.Api.Domain.ActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailFrom")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EmailReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("InterviewEventId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("PreviousDateApplied")
                        .HasColumnType("date");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UndoneAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("ActivityEvents");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CoverLetterText")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateApplied")
                        .HasColumnType("date");

                    b.Property<DateTime?>("InterviewPrepGeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InterviewPrepJson")
                        .HasColumnType("text");

                    b.Property<string>("JobDescriptionText")
                        .HasColumnType("text");

                    b.Property<string>("JobPostingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("LastFollowUpAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TailoredResumeLayout")
                        .HasColumnType("text");

                    b.Property<string>("TailoredResumeText")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DateApplied");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.GmailConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CalendarEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConnectedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PendingScanCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PendingScanResultJson")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GmailConnections");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.InterviewEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CalendarEventId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Debrief")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Reflection")
                        .HasColumnType("text");

                    b.Property<string>("ResearchNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SelfRating")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "ScheduledAtUtc");

                    b.ToTable("InterviewEvents");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.InterviewQuestionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<bool>("Asked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InterviewEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Quality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Suggested")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewEventId", "Side", "Position");

                    b.ToTable("InterviewQuestions");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.MatchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatchedKeywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MissingKeywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Suggestions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UsedTailoredResume")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.HasIndex("ApplicationId", "CreatedAtUtc");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.PrepRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BaselineScore")
                        .HasColumnType("integer");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<string>("Instructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Iterations")
                        .HasColumnType("integer");

                    b.Property<bool?>("ReadyToApply")
                        .HasColumnType("boolean");

                    b.Property<string>("Review")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "StartedAtUtc");

                    b.ToTable("PrepRuns");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtraFacts")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Layout")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.StatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("StatusChanges");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("PlanChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.ActivityEvent", b =>
                {
                    b.HasOne("CareerConnect.Api.Domain.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.Application", b =>
                {
                    b.HasOne("CareerConnect.Api.Domain.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.GmailConnection", b =>
                {
                    b.HasOne("CareerConnect.Api.Domain.User", "User")
                        .WithOne("GmailConnection")
                        .HasForeignKey("CareerConnect.Api.Domain.GmailConnection", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.InterviewEvent", b =>
                {
                    b.HasOne("CareerConnect.Api.Domain.Application", "Application")
                        .WithMany("Interviews")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.InterviewQuestionEntry", b =>
                {
                    b.HasOne("CareerConnect.Api.Domain.InterviewEvent", "Interview")
                        .WithMany("Questions")
                        .HasForeignKey("InterviewEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interview");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.MatchResult", b =>
                {
                    b.HasOne("CareerConnect.Api.Domain.Application", "Application")
                        .WithMany("MatchResults")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerConnect.Api.Domain.Resume", "Resume")
                        .WithMany("MatchResults")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.PrepRun", b =>
                {
                    b.HasOne("CareerConnect.Api.Domain.Application", "Application")
                        .WithMany("PrepRuns")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.Resume", b =>
                {
                    b.HasOne("CareerConnect.Api.Domain.User", "User")
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.StatusChange", b =>
                {
                    b.HasOne("CareerConnect.Api.Domain.Application", "Application")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.Application", b =>
                {
                    b.Navigation("Interviews");

                    b.Navigation("MatchResults");

                    b.Navigation("PrepRuns");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.InterviewEvent", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.Resume", b =>
                {
                    b.Navigation("MatchResults");
                });

            modelBuilder.Entity("CareerConnect.Api.Domain.User", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("GmailConnection");

                    b.Navigation("Resumes");
                });
#pragma warning restore 612, 618
        }
    }
}
